import fs from "node:fs";
import path from "node:path";
import type { ManualTestCase, ManualTestStep } from "../types/manualTest.js";
import type { PlannedAction } from "../types/planner.js";
import { ensureDir } from "../utils/fs.js";
import { logInfo } from "../utils/logger.js";

// ─── Locator conversion ───────────────────────────────────────────────────────

/**
 * Converts a PlannedAction `target` string into a Playwright locator expression.
 *
 * Supported prefixes (same conventions used by the executor):
 *   text:Foo Bar         → page.getByText('Foo Bar')
 *   label:Email          → page.getByLabel('Email')
 *   placeholder:Search   → page.getByPlaceholder('Search')
 *   role:button|Login    → page.getByRole('button', { name: 'Login' })
 *   selector:#foo        → page.locator('#foo')
 *   <anything else>      → page.locator('...')   (bare CSS / XPath)
 */
function targetToLocator(target: string): string {
  const esc = (s: string): string => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

  if (target.startsWith("text:")) {
    return `page.getByText('${esc(target.slice(5))}')`;
  }
  if (target.startsWith("label:")) {
    return `page.getByLabel('${esc(target.slice(6))}')`;
  }
  if (target.startsWith("placeholder:")) {
    return `page.getByPlaceholder('${esc(target.slice(12))}')`;
  }
  if (target.startsWith("role:")) {
    const rest = target.slice(5);
    const pipeIdx = rest.indexOf("|");
    if (pipeIdx === -1) {
      return `page.getByRole('${esc(rest.trim())}')`;
    }
    const role = rest.slice(0, pipeIdx).trim();
    const name = rest.slice(pipeIdx + 1).trim();
    return name
      ? `page.getByRole('${esc(role)}', { name: '${esc(name)}' })`
      : `page.getByRole('${esc(role)}')`;
  }
  if (target.startsWith("selector:")) {
    return `page.locator('${esc(target.slice(9))}')`;
  }
  // Bare CSS selector, attribute selector, or XPath
  return `page.locator('${esc(target)}')`;
}

// ─── Action → code line ───────────────────────────────────────────────────────

/**
 * Converts a single `PlannedAction` into a Playwright `await …;` statement.
 * Returns `null` for actions that should not appear in the generated script
 * (`done`, `out_of_context`, actions without a required target).
 *
 * `valueKey` references are resolved against `dataSet` so the generated script
 * contains the actual value rather than a placeholder key.
 */
function actionToCode(
  action: PlannedAction,
  dataSet: Record<string, string>
): string | null {
  const { action: type, target, value, valueKey } = action;
  const resolvedValue = valueKey ? (dataSet[valueKey] ?? valueKey) : (value ?? "");
  const esc = (s: string): string => s.replace(/\\/g, "\\\\").replace(/'/g, "\\'");

  switch (type) {
    case "goto":
      return `  await page.goto('${esc(target ?? "")}');`;

    case "click":
      if (!target) return null;
      return `  await ${targetToLocator(target)}.click();`;

    case "fill":
      if (!target) return null;
      return `  await ${targetToLocator(target)}.fill('${esc(resolvedValue)}');`;

    case "selectOption":
      if (!target) return null;
      return `  await ${targetToLocator(target)}.selectOption('${esc(resolvedValue)}');`;

    case "press":
      if (!target) return null;
      return `  await ${targetToLocator(target)}.press('${esc(resolvedValue)}');`;

    case "wait": {
      const ms = parseInt(resolvedValue, 10) || 1000;
      return `  await page.waitForTimeout(${ms});`;
    }

    case "assert":
      if (!target) return null;
      return `  await expect(${targetToLocator(target)}).toBeVisible();`;

    case "done":
    case "out_of_context":
    default:
      return null;
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/** One step's worth of resolved actions to include in the generated script. */
export interface StepCodeBlock {
  step: ManualTestStep;
  actions: PlannedAction[];
}

/**
 * Generates a standalone Playwright `.spec.ts` file from the resolved actions
 * collected during a successful run.
 *
 * The file can be executed directly with:
 *   npx playwright test <outputPath>
 *
 * @param testCase   The original test case (for metadata and dataset values).
 * @param stepBlocks Per-step list of resolved `PlannedAction[]` — one entry per passing step.
 * @param outputPath Absolute path where the `.spec.ts` file will be written.
 */
export function generatePlaywrightScript(
  testCase: ManualTestCase,
  stepBlocks: StepCodeBlock[],
  outputPath: string
): void {
  const lines: string[] = [];

  // ── File header ──────────────────────────────────────────────────────────────
  lines.push(`import { test, expect } from '@playwright/test';`);
  lines.push(``);
  lines.push(`// Auto-generated by xray-agent — DO NOT EDIT`);
  lines.push(`// Test: ${testCase.testName}`);
  if (testCase.testCaseKey) {
    lines.push(`// Xray key: ${testCase.testCaseKey}`);
  }
  lines.push(``);

  // ── Test body ────────────────────────────────────────────────────────────────
  const escapedName = testCase.testName.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  lines.push(`test('${escapedName}', async ({ page }) => {`);

  if (testCase.startUrl) {
    const escapedUrl = testCase.startUrl.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    lines.push(`  await page.goto('${escapedUrl}');`);
    lines.push(``);
  }

  // ── Steps ────────────────────────────────────────────────────────────────────
  for (const { step, actions } of stepBlocks) {
    const stepComment = step.action.replace(/\n/g, " ").trim();
    lines.push(`  // Step: ${stepComment}`);

    for (const action of actions) {
      const line = actionToCode(action, testCase.dataSet);
      if (line !== null) {
        lines.push(line);
      }
    }

    lines.push(``);
  }

  lines.push(`});`);
  lines.push(``);

  // ── Write ────────────────────────────────────────────────────────────────────
  ensureDir(path.dirname(outputPath));
  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
  logInfo(`[Codegen] Playwright script written → ${outputPath}`);
}
